[workspace]
members = [
    "crates/ctf-app",
    "crates/ctf-cli",
    "crates/ctf-codecs",
    "crates/ctf-core",
    "crates/ctf-crypto",
    "crates/ctf-launcher",
    "crates/ctf-pwn",
    "crates/ctf-runner",
    "crates/ctf-stego",
    "crates/ctf-web",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0"
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
data-encoding = "2.9"
eframe = { version = "0.33", default-features = true }
egui = "0.33"
hex = "0.4"
md4 = "0.10"
md-5 = "0.10"
regex = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10"
sha2 = "0.10"
sha3 = "0.10"
sm3 = "0.4"
thiserror = "2.0"
toml = "0.9"
urlencoding = "2.1"
