[package]
name = "ctf-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "ctf-tools"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
ctf-core = { path = "../ctf-core" }
ctf-launcher = { path = "../ctf-launcher" }
ctf-runner = { path = "../ctf-runner" }
serde_json.workspace = true
