[package]
name = "ctf-runner"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
ctf-codecs = { path = "../ctf-codecs" }
ctf-core = { path = "../ctf-core" }
ctf-crypto = { path = "../ctf-crypto" }
ctf-pwn = { path = "../ctf-pwn" }
ctf-stego = { path = "../ctf-stego" }
ctf-web = { path = "../ctf-web" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
wait-timeout = "0.2"
